import type { Hex } from '../../color';
import { roles } from '../../roles';

const { bg, fg, border, accent, editor, status, git, ansi, ui } = roles;

export const colors: Record<string, Hex> = {
  // Editor core
  'editor.background': bg.base,
  'editor.foreground': fg.base,
  'editorLineNumber.foreground': fg.faint,
  'editorLineNumber.activeForeground': accent.base,
  'editor.lineHighlightBackground': editor.lineCurrent,
  'editorCursor.foreground': editor.cursor,
  'editorCursor.background': bg.deep,

  // Selection / find / word / bracket
  'editor.selectionBackground': editor.selection,
  'editor.inactiveSelectionBackground': editor.selectionInactive,
  'editor.selectionHighlightBackground': editor.wordHighlight,
  'editor.wordHighlightBackground': editor.wordHighlight,
  'editor.wordHighlightStrongBackground': editor.wordHighlight,
  'editor.wordHighlightTextBackground': editor.wordHighlight,
  'editor.findMatchBackground': editor.findCurrent,
  'editor.findMatchBorder': editor.findCurrentBorder,
  'editor.findMatchHighlightBackground': editor.findMatch,
  'editorBracketMatch.border': editor.bracketMatchBorder,

  // Indent guides / whitespace
  'editorIndentGuide.background': editor.indentGuide,
  'editorIndentGuide.activeBackground': editor.indentGuideActive,
  'editorWhitespace.foreground': fg.faint,

  // Gutter: git + diagnostics
  'editorGutter.background': bg.base,
  'editorGutter.addedBackground': git.added,
  'editorGutter.modifiedBackground': git.modified,
  'editorGutter.deletedBackground': git.deleted,
  'editorError.foreground': status.error,
  'editorWarning.foreground': status.warning,
  'editorInfo.foreground': status.info,
  'editorHint.foreground': status.hint,

  // Overview ruler + minimap
  'editorOverviewRuler.border': border.subtle,
  'editorOverviewRuler.errorForeground': status.error,
  'editorOverviewRuler.warningForeground': status.warning,
  'editorOverviewRuler.infoForeground': status.info,
  'editorOverviewRuler.addedForeground': git.added,
  'editorOverviewRuler.modifiedForeground': git.modified,
  'editorOverviewRuler.deletedForeground': git.deleted,
  'editorOverviewRuler.findMatchForeground': editor.findMatch,
  'editorOverviewRuler.selectionHighlightForeground': editor.wordHighlight,
  'editorOverviewRuler.wordHighlightForeground': editor.wordHighlight,
  'editorOverviewRuler.wordHighlightStrongForeground': editor.wordHighlight,
  'editorOverviewRuler.wordHighlightTextForeground': editor.wordHighlight,
  'editorOverviewRuler.bracketMatchForeground': editor.bracketMatchBorder,
  'minimap.background': bg.base,
  'minimap.findMatchHighlight': editor.findMatch,
  'minimap.selectionHighlight': editor.selection,
  'minimap.selectionOccurrenceHighlight': editor.wordHighlight,
  'minimap.errorHighlight': status.error,
  'minimap.warningHighlight': status.warning,
  'minimap.infoHighlight': status.info,
  'minimapGutter.addedBackground': git.added,
  'minimapGutter.modifiedBackground': git.modified,
  'minimapGutter.deletedBackground': git.deleted,
  'minimapSlider.background': border.subtle,
  'minimapSlider.hoverBackground': border.strong,
  'minimapSlider.activeBackground': border.strong,

  // Scrollbar
  'scrollbarSlider.background': fg.faint,
  'scrollbarSlider.hoverBackground': fg.subtle,
  'scrollbarSlider.activeBackground': fg.muted,

  // Tabs + editorGroupHeader
  'tab.activeBackground': bg.base,
  'tab.activeForeground': fg.base,
  'tab.activeBorder': accent.base,
  'tab.border': border.subtle,
  'tab.inactiveBackground': bg.deep,
  'tab.inactiveForeground': fg.muted,
  'tab.hoverBackground': bg.base,
  'tab.hoverForeground': fg.base,
  'tab.unfocusedActiveBackground': bg.base,
  'tab.unfocusedActiveForeground': fg.base,
  'tab.activeModifiedBorder': fg.muted,
  'tab.inactiveModifiedBorder': fg.muted,
  'tab.unfocusedActiveModifiedBorder': fg.muted,
  'tab.unfocusedInactiveModifiedBorder': fg.muted,
  'editorGroupHeader.tabsBackground': bg.deep,
  'editorGroupHeader.tabsBorder': border.subtle,
  'editorGroupHeader.noTabsBackground': bg.deep,
  'editorGroupHeader.border': border.subtle,
  'editorGroup.border': border.subtle,

  // Panel tabs
  'panelTitle.activeForeground': fg.base,
  'panelTitle.activeBorder': accent.base,
  'panelTitle.inactiveForeground': fg.muted,
  'panelTitle.border': border.subtle,
  'panelTitleBadge.background': bg.raised,
  'panelTitleBadge.foreground': fg.base,

  // Sidebar / list / tree
  'sideBar.background': bg.base,
  'sideBar.foreground': fg.muted,
  'sideBar.border': border.subtle,
  'sideBarTitle.foreground': fg.base,
  'sideBarSectionHeader.background': bg.base,
  'sideBarSectionHeader.foreground': fg.muted,
  'list.hoverBackground': bg.deep,
  'list.hoverForeground': fg.base,
  'list.focusBackground': accent.soft,
  'list.focusForeground': fg.base,
  'list.focusOutline': border.strong,
  'list.activeSelectionBackground': accent.soft,
  'list.activeSelectionForeground': fg.base,
  'list.inactiveSelectionBackground': bg.raised,
  'list.inactiveSelectionForeground': fg.base,
  'list.dropBackground': accent.soft,
  'list.errorForeground': status.error,
  'list.warningForeground': status.warning,
  'list.highlightForeground': editor.findCurrentBorder,
  'list.focusHighlightForeground': editor.findCurrentBorder,
  'tree.indentGuidesStroke': editor.indentGuide,
  'tree.inactiveIndentGuidesStroke': editor.indentGuide,

  // Git decorations in tree
  'gitDecoration.addedResourceForeground': git.added,
  'gitDecoration.modifiedResourceForeground': git.modified,
  'gitDecoration.deletedResourceForeground': git.deleted,
  'gitDecoration.untrackedResourceForeground': git.added,
  'gitDecoration.ignoredResourceForeground': git.ignored,
  'gitDecoration.conflictingResourceForeground': git.conflict,
  'gitDecoration.renamedResourceForeground': git.modified,
  'gitDecoration.stageModifiedResourceForeground': git.modified,
  'gitDecoration.stageDeletedResourceForeground': git.deleted,
  'gitDecoration.submoduleResourceForeground': fg.muted,

  // Activity bar
  'activityBar.background': bg.deep,
  'activityBar.foreground': fg.base,
  'activityBar.inactiveForeground': fg.faint,
  'activityBar.activeBorder': accent.base,
  'activityBar.activeFocusBorder': accent.base,
  'activityBar.border': border.subtle,
  'activityBarBadge.background': bg.raised,
  'activityBarBadge.foreground': fg.base,

  // Status bar
  'statusBar.background': bg.deep,
  'statusBar.foreground': fg.muted,
  'statusBar.border': border.subtle,
  'statusBar.debuggingBackground': bg.deep,
  'statusBar.debuggingForeground': status.warning,
  'statusBar.debuggingBorder': status.warning,
  'statusBar.noFolderBackground': bg.deep,
  'statusBar.noFolderForeground': fg.faint,
  'statusBar.noFolderBorder': border.subtle,
  'statusBarItem.hoverBackground': bg.base,
  'statusBarItem.activeBackground': bg.raised,
  'statusBarItem.prominentBackground': bg.raised,
  'statusBarItem.prominentForeground': fg.base,
  'statusBarItem.errorBackground': status.error,
  'statusBarItem.errorForeground': bg.deep,
  'statusBarItem.warningBackground': status.warning,
  'statusBarItem.warningForeground': bg.deep,
  'statusBarItem.remoteBackground': bg.raised,
  'statusBarItem.remoteForeground': fg.base,
  'statusBarItem.focusBorder': accent.base,

  // Panel / terminal
  'panel.background': bg.base,
  'panel.border': border.subtle,
  'panelInput.border': border.subtle,
  'panelSection.border': border.subtle,
  'panelSectionHeader.background': bg.base,
  'panelSectionHeader.foreground': fg.muted,
  'terminal.background': bg.base,
  'terminal.foreground': fg.base,
  'terminal.border': border.subtle,
  'terminal.selectionBackground': editor.selection,
  'terminal.inactiveSelectionBackground': editor.selectionInactive,
  'terminal.findMatchBackground': editor.findCurrent,
  'terminal.findMatchHighlightBackground': editor.findMatch,

  // Terminal: 16 ANSI
  'terminal.ansiBlack': ansi.black,
  'terminal.ansiRed': ansi.red,
  'terminal.ansiGreen': ansi.green,
  'terminal.ansiYellow': ansi.yellow,
  'terminal.ansiBlue': ansi.blue,
  'terminal.ansiMagenta': ansi.magenta,
  'terminal.ansiCyan': ansi.cyan,
  'terminal.ansiWhite': ansi.white,
  'terminal.ansiBrightBlack': ansi.brightBlack,
  'terminal.ansiBrightRed': ansi.brightRed,
  'terminal.ansiBrightGreen': ansi.brightGreen,
  'terminal.ansiBrightYellow': ansi.brightYellow,
  'terminal.ansiBrightBlue': ansi.brightBlue,
  'terminal.ansiBrightMagenta': ansi.brightMagenta,
  'terminal.ansiBrightCyan': ansi.brightCyan,
  'terminal.ansiBrightWhite': ansi.brightWhite,

  // Inputs
  'input.background': bg.deep,
  'input.foreground': fg.base,
  'input.border': border.subtle,
  'input.placeholderForeground': fg.faint,
  'inputOption.activeBorder': accent.base,
  'inputOption.activeBackground': accent.soft,
  'inputOption.activeForeground': fg.base,
  'inputValidation.errorBackground': bg.deep,
  'inputValidation.errorBorder': status.error,
  'inputValidation.errorForeground': fg.base,
  'inputValidation.warningBorder': status.warning,
  'inputValidation.infoBorder': status.info,

  // Focus / button / badge / dropdown
  focusBorder: accent.base,
  'button.background': accent.base,
  'button.foreground': bg.deep,
  'button.hoverBackground': accent.base,
  'button.secondaryBackground': bg.raised,
  'button.secondaryForeground': fg.base,
  'button.secondaryBorder': border.subtle,
  'button.secondaryHoverBackground': bg.raised,
  'badge.background': bg.raised,
  'badge.foreground': fg.base,
  'dropdown.background': bg.raised,
  'dropdown.foreground': fg.base,
  'dropdown.border': border.strong,
  'dropdown.listBackground': bg.raised,

  // Quick input / command palette
  'quickInput.background': bg.overlay,
  'quickInput.foreground': fg.base,
  'quickInputTitle.background': bg.overlay,
  'quickInputList.focusBackground': accent.soft,
  'quickInputList.focusForeground': fg.base,
  'quickInputList.focusIconForeground': fg.base,

  // Notifications
  'notifications.background': bg.overlay,
  'notifications.foreground': fg.base,
  'notifications.border': border.strong,
  'notificationCenterHeader.background': bg.overlay,
  'notificationsErrorIcon.foreground': status.error,
  'notificationsWarningIcon.foreground': status.warning,
  'notificationsInfoIcon.foreground': status.info,
  'notificationLink.foreground': ui.link,
  'notificationToast.border': border.strong,

  // Peek view
  'peekView.border': border.strong,
  'peekViewTitle.background': bg.deep,
  'peekViewTitleLabel.foreground': fg.base,
  'peekViewTitleDescription.foreground': fg.muted,
  'peekViewEditor.background': bg.overlay,
  'peekViewEditor.matchHighlightBackground': editor.findMatch,
  'peekViewEditor.matchHighlightBorder': border.strong,
  'peekViewEditorGutter.background': bg.overlay,
  'peekViewResult.background': bg.overlay,
  'peekViewResult.fileForeground': fg.base,
  'peekViewResult.lineForeground': fg.muted,
  'peekViewResult.matchHighlightBackground': editor.findMatch,
  'peekViewResult.selectionBackground': accent.soft,
  'peekViewResult.selectionForeground': fg.base,

  // Diff editor
  'diffEditor.border': border.subtle,
  'diffEditor.diagonalFill': border.subtle,
  'diffEditor.insertedLineBackground': editor.diffAdded,
  'diffEditor.insertedTextBackground': editor.diffAddedText,
  'diffEditor.removedLineBackground': editor.diffDeleted,
  'diffEditor.removedTextBackground': editor.diffDeletedText,
  'diffEditorGutter.insertedLineBackground': editor.diffAdded,
  'diffEditorGutter.removedLineBackground': editor.diffDeleted,
  'diffEditorOverview.insertedForeground': git.added,
  'diffEditorOverview.removedForeground': git.deleted,
  'diffEditor.unchangedRegionBackground': bg.deep,
  'diffEditor.move.border': status.info,

  // Merge conflict
  'merge.border': border.strong,
  'merge.currentContentBackground': editor.diffAdded,
  'merge.currentHeaderBackground': editor.diffAddedText,
  'merge.incomingContentBackground': editor.wordHighlight,
  'merge.incomingHeaderBackground': editor.wordHighlight,
  'merge.commonContentBackground': bg.deep,
  'merge.commonHeaderBackground': bg.deep,
  'mergeEditor.conflict.input1.background': editor.diffAdded,
  'mergeEditor.conflict.input2.background': editor.wordHighlight,
  'mergeEditor.conflictingLines.background': editor.conflictBackground,

  // Breadcrumb
  'breadcrumb.background': bg.base,
  'breadcrumb.foreground': fg.muted,
  'breadcrumb.focusForeground': fg.base,
  'breadcrumb.activeSelectionForeground': fg.base,
  'breadcrumbPicker.background': bg.overlay,

  // Title bar
  'titleBar.activeBackground': bg.deep,
  'titleBar.activeForeground': fg.muted,
  'titleBar.inactiveBackground': bg.deep,
  'titleBar.inactiveForeground': fg.faint,
  'titleBar.border': border.subtle,

  // Menu
  'menu.background': bg.overlay,
  'menu.foreground': fg.base,
  'menu.border': border.strong,
  'menu.selectionBackground': accent.soft,
  'menu.selectionForeground': fg.base,
  'menu.separatorBackground': border.subtle,
  'menubar.selectionBackground': bg.raised,

  // Widget / global misc
  'widget.border': border.subtle,
  'sash.hoverBorder': border.strong,
  'textLink.foreground': ui.link,
  'textLink.activeForeground': ui.link,
  'icon.foreground': fg.muted,
  descriptionForeground: fg.muted,
  errorForeground: status.error,
  foreground: fg.base,
  disabledForeground: fg.faint,
  'selection.background': accent.soft,
};
