import type { Hex } from '../../color';
import { roles } from '../../roles';

const { bg, border, fg, accent, status, git, editor, ansi, syntax } = roles;

// Zed paints `<status>.background` as a fill (diff hunks, inlay hints, diagnostics): washes, not solid role colors.
const statusFamily = (name: string, color: Hex, wash: Hex) => ({
  [name]: color,
  [`${name}.background`]: wash,
  [`${name}.border`]: color,
});

export const style = {
  // Core surfaces / text / borders
  background: bg.base,
  'surface.background': bg.deep,
  'elevated_surface.background': bg.overlay,
  'panel.background': bg.base,
  border: border.subtle,
  'border.variant': border.subtle,
  'border.focused': accent.base,
  'border.selected': border.strong,
  'border.disabled': fg.faint,
  text: fg.base,
  'text.muted': fg.muted,
  'text.disabled': fg.faint,
  'text.placeholder': fg.faint,
  'text.accent': accent.base,
  icon: fg.muted,
  'icon.muted': fg.subtle,
  'icon.disabled': fg.faint,
  'icon.placeholder': fg.faint,
  'icon.accent': accent.base,

  // Element / ghost element states
  'element.background': bg.raised,
  'element.hover': bg.deep,
  'element.active': accent.soft,
  'element.selected': accent.soft,
  'element.disabled': fg.faint,
  'ghost_element.hover': bg.deep,
  'ghost_element.active': bg.raised,
  'ghost_element.selected': accent.soft,
  'ghost_element.disabled': fg.faint,

  // Editor
  'editor.background': bg.base,
  'editor.foreground': fg.base,
  'editor.gutter.background': bg.base,
  'editor.line_number': fg.faint,
  'editor.active_line_number': accent.base,
  'editor.active_line.background': editor.lineCurrent,
  'editor.highlighted_line.background': editor.wordHighlight,
  'editor.document_highlight.read_background': editor.wordHighlight,
  'editor.document_highlight.write_background': editor.wordHighlight,
  'editor.document_highlight.bracket_background': editor.bracketMatch,
  'editor.indent_guide': editor.indentGuide,
  'editor.indent_guide_active': editor.indentGuideActive,
  'editor.invisible': fg.faint,
  'editor.wrap_guide': editor.indentGuide,
  'editor.active_wrap_guide': editor.indentGuideActive,
  'editor.subheader.background': bg.deep,
  'search.match_background': editor.findMatch,

  // Status and git
  ...statusFamily('conflict', git.conflict, editor.conflictBackground),
  ...statusFamily('created', git.added, editor.diffAdded),
  ...statusFamily('deleted', git.deleted, editor.diffDeleted),
  ...statusFamily('modified', git.modified, editor.wordHighlight),
  ...statusFamily('renamed', git.modified, editor.wordHighlight),
  ...statusFamily('ignored', git.ignored, bg.raised),
  ...statusFamily('error', status.error, editor.invalidBackground),
  ...statusFamily('warning', status.warning, editor.findMatch),
  ...statusFamily('info', status.info, editor.wordHighlight),
  ...statusFamily('hint', status.hint, bg.raised),
  ...statusFamily('success', status.success, editor.diffAdded),
  ...statusFamily('hidden', fg.faint, bg.raised),
  ...statusFamily('unreachable', fg.subtle, bg.raised),
  ...statusFamily('predictive', fg.subtle, bg.raised),

  // Terminal
  'terminal.background': bg.base,
  'terminal.foreground': fg.base,
  'terminal.bright_foreground': fg.base,
  'terminal.dim_foreground': fg.muted,
  'terminal.ansi.background': bg.base,
  'terminal.ansi.black': ansi.black,
  'terminal.ansi.bright_black': ansi.brightBlack,
  'terminal.ansi.dim_black': ansi.black,
  'terminal.ansi.red': ansi.red,
  'terminal.ansi.bright_red': ansi.brightRed,
  'terminal.ansi.dim_red': ansi.red,
  'terminal.ansi.green': ansi.green,
  'terminal.ansi.bright_green': ansi.brightGreen,
  'terminal.ansi.dim_green': ansi.green,
  'terminal.ansi.yellow': ansi.yellow,
  'terminal.ansi.bright_yellow': ansi.brightYellow,
  'terminal.ansi.dim_yellow': ansi.yellow,
  'terminal.ansi.blue': ansi.blue,
  'terminal.ansi.bright_blue': ansi.brightBlue,
  'terminal.ansi.dim_blue': ansi.blue,
  'terminal.ansi.magenta': ansi.magenta,
  'terminal.ansi.bright_magenta': ansi.brightMagenta,
  'terminal.ansi.dim_magenta': ansi.magenta,
  'terminal.ansi.cyan': ansi.cyan,
  'terminal.ansi.bright_cyan': ansi.brightCyan,
  'terminal.ansi.dim_cyan': ansi.cyan,
  'terminal.ansi.white': ansi.white,
  'terminal.ansi.bright_white': ansi.brightWhite,
  'terminal.ansi.dim_white': ansi.white,

  // Scrollbar / tab / panel / pane / bars
  'scrollbar.thumb.background': fg.faint,
  'scrollbar.thumb.hover_background': fg.subtle,
  'tab_bar.background': bg.deep,
  'tab.active_background': bg.base,
  'tab.inactive_background': bg.deep,
  'panel.focused_border': accent.base,
  'panel.indent_guide': editor.indentGuide,
  'panel.indent_guide_active': editor.indentGuideActive,
  'panel.indent_guide_hover': border.strong,
  'pane.focused_border': accent.base,
  'pane_group.border': border.subtle,
  'title_bar.background': bg.deep,
  'title_bar.inactive_background': bg.deep,
  'status_bar.background': bg.deep,
  'toolbar.background': bg.base,
  'drop_target.background': accent.soft,
  'link_text.hover': syntax.linkText.color,

  players: [{ cursor: accent.base, background: accent.base, selection: editor.selection }],
};
