import type { Hex } from './color';
import { palette } from './palette';

export type Style = { color: Hex; fontStyle?: 'italic' | 'bold' | 'underline' | 'strikethrough' };

export const roles = {
  bg: { deep: palette.bgDeep, base: palette.bgBase, raised: palette.bgRaised, overlay: palette.bgOverlay },
  border: { subtle: palette.borderSubtle, strong: palette.borderStrong },
  fg: { base: palette.fgBase, muted: palette.fgMuted, subtle: palette.fgSubtle, faint: palette.fgFaint },
  accent: { base: palette.aqua, soft: palette.aquaSoft },
  ui: { link: palette.sky },
  status: { error: palette.red, warning: palette.yellow, info: palette.sky, hint: palette.fgSubtle, success: palette.lime },
  git: { added: palette.lime, modified: palette.sky, deleted: palette.red, ignored: palette.fgFaint, conflict: palette.orchid },
  editor: {
    cursor: palette.aqua,
    selection: palette.aquaSoft,
    selectionInactive: palette.borderStrongHalf,
    findMatch: palette.yellowSoft,
    findCurrent: palette.yellowStrong,
    findCurrentBorder: palette.yellow,
    wordHighlight: palette.skyFaint,
    lineCurrent: palette.whiteTrace,
    bracketMatch: palette.aquaFaint,
    bracketMatchBorder: palette.aquaBorder,
    indentGuide: palette.borderSubtle,
    indentGuideActive: palette.fgFaint,
    invalidBackground: palette.redSoft,
    diffAdded: palette.limeFaint,
    diffDeleted: palette.redFaint,
    diffAddedText: palette.limeSoft,
    diffDeletedText: palette.redSoft,
    conflictBackground: palette.orchidSoft,
  },
  syntax: {
    keyword: { color: palette.fuchsia },
    modifier: { color: palette.orchid },
    property: { color: palette.sky },
    string: { color: palette.emerald },
    function: { color: palette.aqua },
    constant: { color: palette.aqua },
    number: { color: palette.peach },
    type: { color: palette.yellow },
    variable: { color: palette.fgBase },
    parameter: { color: palette.fgBase, fontStyle: 'italic' },
    variableSpecial: { color: palette.orchid, fontStyle: 'italic' },
    operator: { color: palette.fgMuted },
    punctuation: { color: palette.fgMuted },
    comment: { color: palette.fgSubtle },
    tag: { color: palette.fuchsia },
    attribute: { color: palette.sky, fontStyle: 'italic' },
    regexp: { color: palette.emerald },
    escape: { color: palette.fuchsia },
    invalid: { color: palette.red, fontStyle: 'underline' },
    deprecated: { color: palette.fgSubtle, fontStyle: 'strikethrough' },
    namespace: { color: palette.fgBase },
    label: { color: palette.orchid },
    preproc: { color: palette.orchid },
    title: { color: palette.aqua, fontStyle: 'bold' },
    linkText: { color: palette.sky },
    linkUri: { color: palette.fgMuted, fontStyle: 'underline' },
    emphasis: { color: palette.fgBase, fontStyle: 'italic' },
    strong: { color: palette.fgBase, fontStyle: 'bold' },
    literal: { color: palette.emerald },
    listMarker: { color: palette.orchid },
    quote: { color: palette.fgSubtle },
  },
  ansi: {
    black: palette.borderStrong, red: palette.red, green: palette.emerald, yellow: palette.yellow,
    blue: palette.blue, magenta: palette.fuchsia, cyan: palette.aqua, white: palette.grayLight,
    brightBlack: palette.fgSubtle, brightRed: palette.redBright, brightGreen: palette.lime, brightYellow: palette.yellowBright,
    brightBlue: palette.sky, brightMagenta: palette.fuchsiaBright, brightCyan: palette.aquaBright, brightWhite: palette.white,
  },
} as const satisfies {
  syntax: Record<string, Style>;
  [group: string]: Record<string, Hex | Style>;
};
